spring:
  application:
    name: spring_application_name_EurekaClientOrder

server:
  port: 8080

eureka:
  client:
    # eureka服务端地址
    service-url:
      defaultZone: http://localhost:8090/EurekaServerSingleTest/

logging:
  config: classpath:logback.xml
